micronaut:
    function:
        name: kuanto-renta

irpf:
    tables:
        2018:
            spain:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    35200: 15,
                    60000: 18.5,
                    1000000: 22.5
                ]
            andalucia:
                tax-table: [
                    12450: 10,
                    20200: 12,
                    28000: 15,
                    35200: 16.5,
                    50000: 19,
                    60000: 19.5,
                    120000: 23.5,
                    1000000: 25.5
                ]
            aragon:
                tax-table: [
                    12450: 10,
                    20200: 12.5,
                    34000: 15.5,
                    50000: 19,
                    60000: 21,
                    70000: 22,
                    90000: 22.5,
                    130000: 23.5,
                    150000: 24.5,
                    1000000: 25
                ]
            asturias:
                tax-table: [
                    12450: 10,
                    17707.20: 12,
                    33007.20: 14,
                    53407.20: 18.5,
                    700000: 21.5,
                    900000: 22.5,
                    175000: 25,
                    1000000: 25.5
                ]
            baleares:
                tax-table: [
                    10000: 9.5,
                    18000: 11.75,
                    30000: 14.75,
                    48000: 17.75,
                    70000: 19.25,
                    90000: 22,
                    120000: 23,
                    175000: 24,
                    1000000: 25
                ]
            canarias:
                tax-table: [
                    12450: 9.5,
                    17707.21: 12,
                    33007.21: 14,
                    53407.21: 18.5,
                    90000.01: 23.5,
                    1000000: 24
                ]
            cantabria:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    34000: 15,
                    46000: 18.5,
                    60000: 19.5,
                    90000: 24.5,
                    1000000: 25.5
                ]
            castillaLaMancha:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    35200: 15,
                    60000: 18.5,
                    1000000: 22.5
                ]
            castillaLeon:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    35200: 14,
                    53407.20: 18.5,
                    1000000: 21.5
                ]
            catalunya:
                tax-table: [
                    17707.20: 12,
                    33007.20: 14,
                    53407.20: 18.5,
                    120000.20: 21.5,
                    175000.20: 23.5,
                    1000000: 25.5
                ]
            extremadura:
                tax-table: [
                    12450: 10.5,
                    20200: 12.5,
                    24200: 15.5,
                    35200: 16.5,
                    60000: 20.5,
                    80200: 23.5,
                    99200: 24,
                    120000: 24.5,
                    1000000: 25
                ]
            galicia:
                tax-table: [
                    12450: 9.5,
                    20200: 11.75,
                    27700: 15.5,
                    35200: 17,
                    47600: 18.5,
                    60000: 20.5,
                    1000000: 22.5
                ]
            madrid:
                tax-table: [
                    12450: 9.5,
                    17707.20: 11.2,
                    33007.20: 13.3,
                    53407.20: 17.9,
                    1000000: 21
                ]
            murcia:
                tax-table: [
                    12450: 10,
                    20200: 12.5,
                    34000: 15.5,
                    60000: 19.5,
                    1000000: 23.5
                ]
            rioja:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    35200: 15,
                    50000: 19,
                    60000: 19.5,
                    120000: 23.5,
                    1000000: 25.5
                ]
            valencia:
                tax-table: [
                    12450: 10,
                    17000: 11,
                    30000: 13.9,
                    50000: 18,
                    65000: 23.5,
                    80000: 24.5,
                    120000: 25,
                    1000000: 25.5
                ]
            ceuta:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    34000: 15,
                    60000: 18.5,
                    1000000: 22.5
                ]
            melilla:
                tax-table: [
                    12450: 9.5,
                    20200: 12,
                    34000: 15,
                    60000: 18.5,
                    1000000: 22.5
                ]